#version: '3.1'
zoo1:
  image: zookeeper
  #restart: always
  hostname: zoo1
  container_name: zookeeper_1
  #domainname: 
  ports:
    - 2181:2181
  volumes:
    - ${PWD}/data:/data
    - ${PWD}/datalog:/datalog
    - ${PWD}/logs:/logs
  #environment:
    #ZOO_MY_ID: 1
      #ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888