elasticsearch:
#  restart: always
  image: "elasticsearch:5.6-alpine"
  container_name: es
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - "$PWD/data/:/usr/share/elasticsearch/data/"
#    - "/Users/Johnny/dev/dockers/elasticsearch/config/:/usr/share/elasticsearch/config/"
    - "$PWD/logs/:/user/share/elasticsearch/log/"
  environment:
    ES_JAVA_OPTS: "-Xms256m -Xmx256m"
#  mem_limit: 128m


# Note:
#macOS with Docker for Mac
#The vm.max_map_count setting must be set within the xhyve virtual machine:
#$ screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty
#Just press enter and configure the sysctl setting as you would for Linux:
#sysctl -w vm.max_map_count=262144
# https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
