mariadb:
  image: "mariadb"
#  restart: always
  volumes:
    - "$PWD/data:/var/lib/mysql"
    - "$PWD/conf:/etc/mysql/conf.d"
  ports:
    - "3306:3306"
  privileged: true
  environment:
    - "TIMEZONE:Asia/Shanghai"
    - "MYSQL_ROOT_PASSWORD:admin"
  mem_limit: 128m
